apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-scenario-v2
    owner: Idris
  name: devops-scenario-v2
  namespace: NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-scenario-v2
  strategy: {}
  template:
    metadata:
      labels:
        app: devops-scenario-v2
    spec:
      containers:
      - image: IMAGE_NAME
        name: devops-scenario-v2-image
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

